{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "47e80b27_f12a4df3",
        "filename": "/COMMIT_MSG",
        "patchSetId": 3
      },
      "lineNbr": 11,
      "author": {
        "id": 1000086
      },
      "writtenOn": "2023-06-22T08:10:52Z",
      "side": 1,
      "message": "Can you point me the commit which is complaining this CI error. Interestingly , recent commits not thrown this error.",
      "range": {
        "startLine": 9,
        "startChar": 0,
        "endLine": 11,
        "endChar": 58
      },
      "revId": "0cfe1a2ee0fd9ecf69d340f7bad4a2a9c1b04d32",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}