{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "9f91c5bc_d1cbf631",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1000233
      },
      "writtenOn": "2025-01-29T23:26:44Z",
      "side": 1,
      "message": "The CI errors are pre-existing",
      "revId": "6e7262974115f1cc632e6f7a5be12114ee4af8dc",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}